.test_template: &UnitTests
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "twoD"
  script:
    # Run the tests. 
    - julia -e 'using Pkg; Pkg.add(; path=pwd()); Pkg.build("Meshfree4ScalarEq"); Pkg.test("Meshfree4ScalarEq"; coverage = true)'
    # Comment out below if you do not want coverage results.
    - julia -e 'using Pkg; Pkg.add("Coverage");
      import Meshfree4ScalarEq; cd(joinpath(dirname(pathof(Meshfree4ScalarEq)), ".."));
      using Coverage; cl, tl = get_summary(process_folder());
      println("(", cl/tl*100, "%) covered")'

# images comes from Docker hub
test:1.10.2:
  image: julia:1.10.2
  <<: *UnitTests


